// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var Belt_Result = require("rescript/lib/js/belt_Result.js");
var JsonRecordEventGateway = require("../src/JsonRecordEventGateway.bs.js");

let path = require('path');
;

var filePath = (path.resolve(module.path, '..', '..', '..', '..', 'test.json'));

var parseUnknown = (function (u) {
    return ((u === 'event1') || (u === 'event2'))
      ? u
      : undefined;
  });

var TestEvent = {
  parseUnknown: parseUnknown
};

var TestJsonRecordConf = {
  fileName: filePath
};

var TestJsonRecordEventGateway = JsonRecordEventGateway.MakeJsonRecordEventGateway(TestEvent, TestJsonRecordConf);

console.log(Belt_Result.flatMap(Belt_Result.flatMap(Belt_Result.map(Belt_Result.flatMap(Belt_Result.flatMap(Belt_Result.flatMap({
                              TAG: /* Ok */0,
                              _0: undefined
                            }, (function (param) {
                                return Curry._1(TestJsonRecordEventGateway.createTableIfNotExist, undefined);
                              })), (function (param) {
                            return Curry._1(TestJsonRecordEventGateway.insertEvents, [
                                        "event1",
                                        "event2",
                                        "event1"
                                      ]);
                          })), (function (param) {
                        return Belt_Result.map(Curry._2(TestJsonRecordEventGateway.getEvents, 0, undefined), (function (prim) {
                                      console.log(prim);
                                    }));
                      })), (function (param) {
                    console.log("---");
                  })), (function (param) {
                return Belt_Result.map(Curry._2(TestJsonRecordEventGateway.getEvents, 1, 1), (function (prim) {
                              console.log(prim);
                            }));
              })), (function (param) {
            return Curry._1(TestJsonRecordEventGateway.dropTableIfExist, undefined);
          })));

exports.filePath = filePath;
exports.TestEvent = TestEvent;
exports.TestJsonRecordConf = TestJsonRecordConf;
exports.TestJsonRecordEventGateway = TestJsonRecordEventGateway;
/*  Not a pure module */
